project:
  type: website
  output-dir: docs
  title: STEMcoding
  resources:
    - CNAME
    - vaxgame

website:
  favicon: img/stemcoding_favicon_final.png
  navbar:
    title: false
    left:
      - text: '<img src="../img/STEMcoding_logo_transparent.png" alt="STEMcoding Logo" style="height: 38px; margin-top: -10px;">'
        href: index.qmd
      - about.qmd    
      - activities.qmd
      - href: people.qmd
        text: People
      - href: feed.qmd
        text: Feed
      - calendar.qmd
      - datascience.qmd
      - publications.qmd
    tools:
      - icon: youtube
        href: https://www.youtube.com/STEMcoding
      - icon: instagram
        href: https://www.instagram.com/stemcoding/  
      - icon: facebook
        href: https://www.facebook.com/stemcodingproject
      - icon: mastodon 
        href: https://mastodon.social/@STEMcoding
      - icon: discord
        href: https://discord.gg/bsWgqcqwCE        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    sidebar:
      - id: main-sidebar
        contents:
          - section: "On this page"
            contents: auto
          - section: "Social Feed"
            contents: |
              <iframe allowfullscreen sandbox="allow-top-navigation allow-scripts allow-popups allow-popups-to-escape-sandbox" width="100%" height="400" src="https://mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Fmastodon.social%2Fusers%2Fstemcoding&theme=light&size=100&header=false&replies=false&boosts=true" style="border: 1px solid #ccc; border-radius: 8px;"></iframe>



